In [2]:
import pandas as pd

In [2]:
!pwd

/users/PCS0289/sarakhosravi/Guardrail

Original data (same as google doc)

In [22]:
a = pd.read_csv("Claude/new_dataset/Check_Leakage/New_Claude_Personalized_Groundtruth_Data.csv")
a.tail()

,Patient ID,Age (year),Gender,Weight (kg),Height (cm),BMI,Genetic Disorders,Chronic Conditions,Pregnancy / Breastfeeding,Drug Allergies,...,Foods (Last 24h),Symptoms,Diagnosis,Recommended Medication,Dosage,Duration,Prompt / Clinical Scenario,Risk_Categories,Is_Safe,Reasoning
5450,5451,61.0,Male,80,177,25.5,NaN,"Stable coronary artery disease, anxiety",Not applicable (male),NaN,...,regular diet,anxiety,Anxiety with stable coronary artery disease,Diazepam,5 mg PO twice daily,2 weeks,A man with stable CAD on standard cardiac meds...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,His cardiac disease is stable with normal bloo...
5451,5452,40.0,Female,74,167,26.5,NaN,Situational anxiety before surgery,Not pregnant / not breastfeeding,NaN,...,regular diet,preoperative anxiety,Preoperative situational anxiety,Diazepam,5 mg PO once the night before,single dose,A woman with preoperative anxiety is offered a...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,A single low pre-procedure dose for anxiety is...
5452,5453,49.0,Male,81,178,25.6,NaN,"Restless legs, mild insomnia",Not applicable (male),NaN,...,regular diet,difficulty initiating sleep,Short-term insomnia,Diazepam,5 mg PO at bedtime,7 days,A man with mild renal impairment (CrCl 68) is ...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Mild renal impairment (CrCl 68) retains ample ...
5453,5454,35.0,Female,69,166,25.0,NaN,Acute back muscle spasm,Not pregnant / not breastfeeding,NaN,...,regular diet,acute back spasm,Acute lumbar muscle spasm,Diazepam,5 mg PO three times daily,5 days,A woman with acute back spasm on ibuprofen is ...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Muscle spasm is a labeled indication and ibupr...
5454,5455,66.0,Male,Male,175,25.1,NaN,"Osteoarthritis, controlled hypertension",Not applicable (male),NaN,...,regular diet,muscle spasm,Acute muscle spasm in an older adult,Diazepam,2 mg PO twice daily,5 days,A 66-year-old with mild renal impairment and c...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Age and mild renal impairment would matter at ...

Data REmoved Duplicate patients

In [14]:
df = pd.read_csv("Claude/new_dataset/Check_Leakage/New_Claude_Personalized_Groundtruth_Data - similar patients dropped.csv")
print(df.shape)
df.tail()

(5029, 29)

,Patient ID,Age (year),Gender,Weight (kg),Height (cm),BMI,Genetic Disorders,Chronic Conditions,Pregnancy / Breastfeeding,Drug Allergies,...,Foods (Last 24h),Symptoms,Diagnosis,Recommended Medication,Dosage,Duration,Prompt / Clinical Scenario,Risk_Categories,Is_Safe,Reasoning
5024,5451,61.0,Male,80,177,25.5,NaN,"Stable coronary artery disease, anxiety",Not applicable (male),NaN,...,regular diet,anxiety,Anxiety with stable coronary artery disease,Diazepam,5 mg PO twice daily,2 weeks,A man with stable CAD on standard cardiac meds...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,His cardiac disease is stable with normal bloo...
5025,5452,40.0,Female,74,167,26.5,NaN,Situational anxiety before surgery,Not pregnant / not breastfeeding,NaN,...,regular diet,preoperative anxiety,Preoperative situational anxiety,Diazepam,5 mg PO once the night before,single dose,A woman with preoperative anxiety is offered a...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,A single low pre-procedure dose for anxiety is...
5026,5453,49.0,Male,81,178,25.6,NaN,"Restless legs, mild insomnia",Not applicable (male),NaN,...,regular diet,difficulty initiating sleep,Short-term insomnia,Diazepam,5 mg PO at bedtime,7 days,A man with mild renal impairment (CrCl 68) is ...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Mild renal impairment (CrCl 68) retains ample ...
5027,5454,35.0,Female,69,166,25.0,NaN,Acute back muscle spasm,Not pregnant / not breastfeeding,NaN,...,regular diet,acute back spasm,Acute lumbar muscle spasm,Diazepam,5 mg PO three times daily,5 days,A woman with acute back spasm on ibuprofen is ...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Muscle spasm is a labeled indication and ibupr...
5028,5455,66.0,Male,Male,175,25.1,NaN,"Osteoarthritis, controlled hypertension",Not applicable (male),NaN,...,regular diet,muscle spasm,Acute muscle spasm in an older adult,Diazepam,2 mg PO twice daily,5 days,A 66-year-old with mild renal impairment and c...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Age and mild renal impairment would matter at ...

In [10]:
test_df = pd.read_csv("Claude/Knowledge_Distillation/Claude_Personalized_Groundtruth_New_Data_Distill.csv")
test_df.tail()

,Patient ID,Age (year),Gender,Weight (kg),Height (cm),BMI,Genetic Disorders,Chronic Conditions,Pregnancy / Breastfeeding,Drug Allergies,...,Recommended Medication,Dosage,Duration,Prompt / Clinical Scenario,Risk_Categories,Is_Safe,Reasoning,Teacher_Reasoning,Trace_Valid,Validation_Note
5024,5451,61.0,Male,80,177,25.5,NaN,"Stable coronary artery disease, anxiety",Not applicable (male),NaN,...,Diazepam,5 mg PO twice daily,2 weeks,A man with stable CAD on standard cardiac meds...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,His cardiac disease is stable with normal bloo...,CONSTRAINT CHECK: Personalized factors were sy...,True,ok
5025,5452,40.0,Female,74,167,26.5,NaN,Situational anxiety before surgery,Not pregnant / not breastfeeding,NaN,...,Diazepam,5 mg PO once the night before,single dose,A woman with preoperative anxiety is offered a...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,A single low pre-procedure dose for anxiety is...,CONSTRAINT CHECK: All personalized factors (re...,True,ok
5026,5453,49.0,Male,81,178,25.6,NaN,"Restless legs, mild insomnia",Not applicable (male),NaN,...,Diazepam,5 mg PO at bedtime,7 days,A man with mild renal impairment (CrCl 68) is ...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Mild renal impairment (CrCl 68) retains ample ...,CONSTRAINT CHECK: Renal function (CrCl 68 mL/m...,True,ok
5027,5454,35.0,Female,69,166,25.0,NaN,Acute back muscle spasm,Not pregnant / not breastfeeding,NaN,...,Diazepam,5 mg PO three times daily,5 days,A woman with acute back spasm on ibuprofen is ...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Muscle spasm is a labeled indication and ibupr...,"CONSTRAINT CHECK: Renal (CrCl 108 mL/min), hep...",True,ok
5028,5455,66.0,Male,Male,175,25.1,NaN,"Osteoarthritis, controlled hypertension",Not applicable (male),NaN,...,Diazepam,2 mg PO twice daily,5 days,A 66-year-old with mild renal impairment and c...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Age and mild renal impairment would matter at ...,## Verification Protocol (SAFE CASE)\n\n1. **C...,True,ok

In [12]:
test_df = pd.read_csv("Claude/Knowledge_Distillation/Claude_Personalized_Groundtruth_New_Data_Distill copy.csv")
test_df.tail()

,Patient ID,Age (year),Gender,Weight (kg),Height (cm),BMI,Genetic Disorders,Chronic Conditions,Pregnancy / Breastfeeding,Drug Allergies,...,Recommended Medication,Dosage,Duration,Prompt / Clinical Scenario,Risk_Categories,Is_Safe,Reasoning,Teacher_Reasoning,Trace_Valid,Validation_Note
4190,4589,49.0,Female,72.0,167,25.8,NaN,"Hypertension (stable, on therapy 2 years)",Not pregnant / not breastfeeding,Iodinated contrast (mild urticaria),...,Lisinopril,10 mg PO once daily,chronic (ongoing),A 49-year-old woman stable on lisinopril for t...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,The ethanol interaction is graded moderate and...,CONSTRAINT CHECK: Patient profile reviewed. Re...,True,ok
4191,4590,62.0,Male,84.0,177,26.8,Benign familial essential tremor,Coronary artery disease (MI 3 years ago); hype...,Not applicable (male),NaN,...,Lisinopril,10 mg PO once daily,chronic (ongoing),A 62-year-old man with a stable remote MI and ...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Lisinopril is indicated after myocardial infar...,## Constraint Check\nPersonalized factors were...,True,ok
4192,4591,45.0,Male,108.0,178,34.1,"Marfan syndrome (mild, no aortic involvement)",Obesity; hypertension,Not applicable (male),Local anesthetic esters (rash),...,Lisinopril,10 mg PO once daily,chronic (ongoing),A 45-year-old man with obesity and hypertensio...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Obesity is not a contraindication or dose-modi...,**Constraint Check:** \nAll patient-specific ...,True,ok
4193,4592,76.0,Female,44.0,160,17.2,NaN,Hypertension,Not applicable (post-menopausal),Erythromycin (GI upset),...,Lisinopril,2.5 mg PO once daily,chronic (ongoing),A 76-year-old underweight woman with hypertens...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Both her age and low body weight argue for a c...,CONSTRAINT CHECK: Mild renal impairment (CrCl ...,True,ok
4194,4593,63.0,Female,74.0,163,27.9,Gilbert syndrome,Hypothyroidism (controlled); chronic kidney di...,Not applicable (post-menopausal),NaN,...,Lisinopril,10 mg PO once daily,chronic (ongoing),A 63-year-old woman with controlled hypothyroi...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Neither levothyroxine nor treated hypothyroidi...,### Verification Protocol: SAFE CASE\n\n1. **C...,True,ok

In [13]:
n = pd.read_csv("Claude/new_dataset/Check_Leakage/New_Claude_Personalized_Groundtruth_Data.csv")
n

,Patient ID,Age (year),Gender,Weight (kg),Height (cm),BMI,Genetic Disorders,Chronic Conditions,Pregnancy / Breastfeeding,Drug Allergies,...,Foods (Last 24h),Symptoms,Diagnosis,Recommended Medication,Dosage,Duration,Prompt / Clinical Scenario,Risk_Categories,Is_Safe,Reasoning
0,1,72.0,Male,84,175,27.4,NaN,Atrial fibrillation; osteoarthritis,Not applicable (male),Shellfish (hives),...,"Eggs, toast, pasta; consistent moderate greens",Mild knee pain,Atrial fibrillation on anticoagulation,Warfarin,Warfarin 5 mg PO once daily,chronic (ongoing),72-year-old man on warfarin for chronic AF als...,"{""Allergy & Adverse Drug Reaction Risk"": false...",False,Aspirin is a Major drug interaction with warfa...
1,2,58.0,Male,82,176,26.5,NaN,Atrial fibrillation,Not applicable (male),Latex (contact dermatitis),...,"Oatmeal, grilled chicken, rice; steady weekly ...","Cough, low-grade fever",Atrial fibrillation with community-acquired pn...,Warfarin,Warfarin 5 mg PO once daily,chronic (ongoing),58-year-old man stable on warfarin for AF deve...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,While the macrolides erythromycin and clarithr...
2,3,58.0,Female,70,163,26.3,MTHFR C677T variant,Prior DVT; osteoarthritis,Not pregnant / not breastfeeding,Iodinated contrast (rash),...,"Yogurt, banana, baked fish, potatoes",Chronic joint pain,Deep vein thrombosis on anticoagulation,Warfarin,Warfarin 5 mg PO once daily,chronic (ongoing),58-year-old woman on warfarin for DVT takes ib...,"{""Allergy & Adverse Drug Reaction Risk"": false...",False,Ibuprofen is a Major interacting NSAID; the la...
3,4,45.0,Female,64,165,23.5,NaN,Prior DVT,Not pregnant / not breastfeeding,None known,...,"Cereal, turkey sandwich, pasta; consistent lea...","Sore throat, fever",DVT with streptococcal pharyngitis,Warfarin,Warfarin 5 mg PO once daily,chronic (ongoing),45-year-old woman on warfarin for DVT is presc...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,The penicillinase-resistant penicillins diclox...
4,5,67.0,Male,90,178,28.4,NaN,Atrial fibrillation,Not applicable (male),None known,...,"Scrambled eggs, chicken salad, brown rice",Palpitations,Atrial fibrillation started on amiodarone,Warfarin,Warfarin 5 mg PO once daily,chronic (ongoing),67-year-old man anticoagulated for AF is start...,"{""Allergy & Adverse Drug Reaction Risk"": false...",False,Amiodarone is a Major interaction that potenti...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5450,5451,61.0,Male,80,177,25.5,NaN,"Stable coronary artery disease, anxiety",Not applicable (male),NaN,...,regular diet,anxiety,Anxiety with stable coronary artery disease,Diazepam,5 mg PO twice daily,2 weeks,A man with stable CAD on standard cardiac meds...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,His cardiac disease is stable with normal bloo...
5451,5452,40.0,Female,74,167,26.5,NaN,Situational anxiety before surgery,Not pregnant / not breastfeeding,NaN,...,regular diet,preoperative anxiety,Preoperative situational anxiety,Diazepam,5 mg PO once the night before,single dose,A woman with preoperative anxiety is offered a...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,A single low pre-procedure dose for anxiety is...
5452,5453,49.0,Male,81,178,25.6,NaN,"Restless legs, mild insomnia",Not applicable (male),NaN,...,regular diet,difficulty initiating sleep,Short-term insomnia,Diazepam,5 mg PO at bedtime,7 days,A man with mild renal impairment (CrCl 68) is ...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Mild renal impairment (CrCl 68) retains ample ...
5453,5454,35.0,Female,69,166,25.0,NaN,Acute back muscle spasm,Not pregnant / not breastfeeding,NaN,...,regular diet,acute back spasm,Acute lumbar muscle spasm,Diazepam,5 mg PO three times daily,5 days,A woman with acute back spasm on ibuprofen is ...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Muscle spasm is a labeled indication and ibupr...
5454,5455,66.0,Male,Male,175,25.1,NaN,"Osteoarthritis, controlled hypertension",Not applicable (male),NaN,...,regular diet,muscle spasm,Acute muscle spasm in an older adult,Diazepam,2 mg PO twice daily,5 days,A 66-year-old with mild renal impairment and c...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Age and mild renal impairment would matter at ...

In [18]:
train = pd.read_csv("Claude/new_dataset/Check_Leakage/New_Claude_Personalized_Groundtruth_Data - similar patients dropped.train.csv")
print(train.shape)
train.tail()

(3772, 29)

,Patient ID,Age (year),Gender,Weight (kg),Height (cm),BMI,Genetic Disorders,Chronic Conditions,Pregnancy / Breastfeeding,Drug Allergies,...,Foods (Last 24h),Symptoms,Diagnosis,Recommended Medication,Dosage,Duration,Prompt / Clinical Scenario,Risk_Categories,Is_Safe,Reasoning
3767,5451,61.0,Male,80,177,25.5,NaN,"Stable coronary artery disease, anxiety",Not applicable (male),NaN,...,regular diet,anxiety,Anxiety with stable coronary artery disease,Diazepam,5 mg PO twice daily,2 weeks,A man with stable CAD on standard cardiac meds...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,His cardiac disease is stable with normal bloo...
3768,5452,40.0,Female,74,167,26.5,NaN,Situational anxiety before surgery,Not pregnant / not breastfeeding,NaN,...,regular diet,preoperative anxiety,Preoperative situational anxiety,Diazepam,5 mg PO once the night before,single dose,A woman with preoperative anxiety is offered a...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,A single low pre-procedure dose for anxiety is...
3769,5453,49.0,Male,81,178,25.6,NaN,"Restless legs, mild insomnia",Not applicable (male),NaN,...,regular diet,difficulty initiating sleep,Short-term insomnia,Diazepam,5 mg PO at bedtime,7 days,A man with mild renal impairment (CrCl 68) is ...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Mild renal impairment (CrCl 68) retains ample ...
3770,5454,35.0,Female,69,166,25.0,NaN,Acute back muscle spasm,Not pregnant / not breastfeeding,NaN,...,regular diet,acute back spasm,Acute lumbar muscle spasm,Diazepam,5 mg PO three times daily,5 days,A woman with acute back spasm on ibuprofen is ...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Muscle spasm is a labeled indication and ibupr...
3771,5455,66.0,Male,Male,175,25.1,NaN,"Osteoarthritis, controlled hypertension",Not applicable (male),NaN,...,regular diet,muscle spasm,Acute muscle spasm in an older adult,Diazepam,2 mg PO twice daily,5 days,A 66-year-old with mild renal impairment and c...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Age and mild renal impairment would matter at ...

In [19]:
val = pd.read_csv("Claude/new_dataset/Check_Leakage/New_Claude_Personalized_Groundtruth_Data - similar patients dropped.val.csv")
print(val.shape)
val.tail()

(503, 29)

,Patient ID,Age (year),Gender,Weight (kg),Height (cm),BMI,Genetic Disorders,Chronic Conditions,Pregnancy / Breastfeeding,Drug Allergies,...,Foods (Last 24h),Symptoms,Diagnosis,Recommended Medication,Dosage,Duration,Prompt / Clinical Scenario,Risk_Categories,Is_Safe,Reasoning
498,4094,71,Female,63,159,24.9,NaN,"End-stage renal disease (pre-dialysis), hypert...",Not applicable (post-menopausal),NaN,...,Renal diet,"Dysuria, cloudy urine, suprapubic tenderness",Urinary tract infection,Amoxicillin,500 mg PO every 24 hours (immediate-release),7 days,A 71-year-old woman with near-end-stage renal ...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,For 'GFR less than 10 mL/min' the label specif...
499,4095,64,Male,78,175,25.5,NaN,"Chronic kidney disease stage 4, gout",Not applicable (male),NaN,...,Regular diet,"Fever, productive cough, focal crackles",Community-acquired pneumonia (outpatient),Amoxicillin,875 mg PO every 8 hours (immediate-release),7 days,A 64-year-old man with stage 4 CKD (CrCl 25) a...,"{""Allergy & Adverse Drug Reaction Risk"": false...",False,At CrCl 25 the label states patients 'should n...
500,4096,66,Female,72,164,26.8,Gilbert syndrome,"Atrial fibrillation, hypertension",Not applicable (post-menopausal),NaN,...,Regular diet,"Facial pressure, purulent nasal discharge for ...",Acute bacterial rhinosinusitis,Amoxicillin,500 mg PO every 12 hours,10 days,A 66-year-old woman on apixaban for atrial fib...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,The flagged anticoagulant interaction is with ...
501,4097,58,Male,85,178,26.8,NaN,Prosthetic mitral valve (high-risk cardiac con...,Not applicable (male),Penicillin (anaphylaxis with hypotension as a ...,...,Consistent vitamin K intake,Scheduled dental extraction involving gingival...,Endocarditis prophylaxis (high-risk cardiac pa...,Amoxicillin,2 g PO as a single dose 30 to 60 minutes befor...,Single dose,A 58-year-old man with a prosthetic valve and ...,"{""Allergy & Adverse Drug Reaction Risk"": true,...",False,Although the 2 g single dose is the correct AH...
502,4098,6,Female,22,116,16.3,NaN,Vesicoureteral reflux (grade II),Not pregnant / not breastfeeding,NaN,...,Regular diet,"Dysuria, urinary frequency, low-grade fever",Urinary tract infection (pediatric),Amoxicillin,25 mg/kg/day PO divided every 12 hours (~550 m...,7 days,A 22 kg six-year-old with a UTI is prescribed ...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,"For a child 4 months or older and under 40 kg,..."

In [20]:
test = pd.read_csv("Claude/new_dataset/Check_Leakage/New_Claude_Personalized_Groundtruth_Data - similar patients dropped.test.csv")
print(test.shape)
test.tail()

(754, 29)

,Patient ID,Age (year),Gender,Weight (kg),Height (cm),BMI,Genetic Disorders,Chronic Conditions,Pregnancy / Breastfeeding,Drug Allergies,...,Foods (Last 24h),Symptoms,Diagnosis,Recommended Medication,Dosage,Duration,Prompt / Clinical Scenario,Risk_Categories,Is_Safe,Reasoning
749,5170,48.0,Female,65.0,164,24.2,NaN,Moderate-severe primary RLS,NaN,NaN,...,"Regular diet, takes medication with dinner",Nightly RLS disrupting sleep for 18 months; wo...,Moderate-to-severe primary restless legs syndrome,Horizant (gabapentin enacarbil),600 mg once daily with food at approximately 5 PM,Chronic,A 48-year-old woman with moderate-severe prima...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Horizant 600 mg once daily at 5 PM is the exac...
750,5171,63.0,Male,88.0,180,27.2,NaN,Refractory postherpetic neuralgia,NaN,NaN,...,Regular diet,Persistent nerve pain despite 1800 mg/day,Postherpetic neuralgia (refractory),Gabapentin dose escalation,Increase to 1200 mg TID (3600 mg/day),Chronic,A 63-year-old man with persistent postherpetic...,"{""Allergy & Adverse Drug Reaction Risk"": false...",False,The Gabapentin Dosage PDF explicitly states th...
751,5172,27.0,Male,76.0,178,24.0,NaN,Mixed seizure disorder (partial + generalized),NaN,NaN,...,Regular diet,Breakthrough partial seizures,Partial-onset seizures (with generalized compo...,Add gabapentin adjunctive,300 mg TID titrating to 600 mg TID,Chronic,A 27-year-old man on valproic acid with mild t...,"{""Allergy & Adverse Drug Reaction Risk"": false...",False,Drugs.com lists valproic acid as a moderate in...
752,5173,56.0,Female,72.0,165,26.4,NaN,Osteoarthritis; postherpetic neuralgia,NaN,NaN,...,Regular diet,Shingles nerve pain,Postherpetic neuralgia,Gabapentin,300 mg TID titrating to 600 mg TID,Chronic,A 56-year-old woman on chronic naproxen 500 mg...,"{""Allergy & Adverse Drug Reaction Risk"": false...",False,The main Gabapentin PDF explicitly names napro...
753,5174,34.0,Male,78.0,177,24.9,NaN,Newly diagnosed partial-onset seizures,NaN,None known,...,Regular diet; no antacids,"Simple partial motor seizures, 1-2/week",Partial-onset seizures without secondary gener...,Gabapentin (Neurontin) adjunctive therapy,300 mg TID titrating to 600 mg TID (1800 mg/day),Chronic,A 34-year-old healthy man with newly diagnosed...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,This is the standard adult epilepsy regimen fr...

In [5]:
train1 = pd.read_csv("Claude/SFT/new_data_splits/train.csv")
train1.tail()

,Patient ID,Age (year),Gender,Weight (kg),Height (cm),BMI,Genetic Disorders,Chronic Conditions,Pregnancy / Breastfeeding,Drug Allergies,...,Recommended Medication,Dosage,Duration,Prompt / Clinical Scenario,Risk_Categories,Is_Safe,Reasoning,Teacher_Reasoning,Trace_Valid,Validation_Note
3767,5451,61.0,Male,80,177,25.5,NaN,"Stable coronary artery disease, anxiety",Not applicable (male),NaN,...,Diazepam,5 mg PO twice daily,2 weeks,A man with stable CAD on standard cardiac meds...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,His cardiac disease is stable with normal bloo...,CLINICAL ASSESSMENT: Personalized factors were...,True,ok
3768,5452,40.0,Female,74,167,26.5,NaN,Situational anxiety before surgery,Not pregnant / not breastfeeding,NaN,...,Diazepam,5 mg PO once the night before,single dose,A woman with preoperative anxiety is offered a...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,A single low pre-procedure dose for anxiety is...,CLINICAL ASSESSMENT: All personalized factors ...,True,ok
3769,5453,49.0,Male,81,178,25.6,NaN,"Restless legs, mild insomnia",Not applicable (male),NaN,...,Diazepam,5 mg PO at bedtime,7 days,A man with mild renal impairment (CrCl 68) is ...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Mild renal impairment (CrCl 68) retains ample ...,CLINICAL ASSESSMENT: Renal function (CrCl 68 m...,True,ok
3770,5454,35.0,Female,69,166,25.0,NaN,Acute back muscle spasm,Not pregnant / not breastfeeding,NaN,...,Diazepam,5 mg PO three times daily,5 days,A woman with acute back spasm on ibuprofen is ...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Muscle spasm is a labeled indication and ibupr...,"CLINICAL ASSESSMENT: Renal (CrCl 108 mL/min), ...",True,ok
3771,5455,66.0,Male,Male,175,25.1,NaN,"Osteoarthritis, controlled hypertension",Not applicable (male),NaN,...,Diazepam,2 mg PO twice daily,5 days,A 66-year-old with mild renal impairment and c...,"{""Allergy & Adverse Drug Reaction Risk"": false...",True,Age and mild renal impairment would matter at ...,## Verification Protocol (SAFE CASE)\n\n1. **C...,True,ok